import { Poppins } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Specify the weights you need
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      className={clsx(
        "h-full scroll-smooth bg-white antialiased",
        poppins.variable
      )}
      lang="en"
    >
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
